version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget_db
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: postgres
    ports:
      - "5432:5432"
